### PR TITLE
FIX: Shape & Needle Pointer Interactivity ListView

### PR DESCRIPTION
**Pull request by Afroz-Shaikh**
# Changes 
- Fixed an issue where Shape Pointer & Needle Pointers were not interactive in ListViews 

https://github.com/GeekyAnts/GaugesFlutter/assets/50929682/11b090a8-1ecb-4c43-85b4-dc11b00816da

### CODE REVIEW

**Comment by hasnentai** [comment]
I think haveing the indicator number in between will make more sense to prove its working

**Comment by Afroz-Shaikh** [comment]
> I think haveing the indicator number in between will make more sense to prove its working

Sure @hasnentai, 

https://github.com/GeekyAnts/GaugesFlutter/assets/50929682/e47621ff-8ce0-4fff-be9a-bb80787b245d

**Comment by hasnentai** [comment]
@Afroz-Shaikh Hi,
Can you also try to add multiple guages in the list and see all are working fine ?

**Comment by Afroz-Shaikh** [comment]
> @Afroz-Shaikh Hi, Can you also try to add multiple guages in the list and see all are working fine ?

Yes, @hasnentai  I checked it, ListViews were the main thing causing the problem!! 

https://github.com/GeekyAnts/GaugesFlutter/assets/50929682/0c393498-206c-431d-ae9c-1b98e4154c4a

**Comment by crissCM** [comment]
It still doesn't work for me. Could you please share a full working example?

**Comment by hasnentai** [comment]
We haven't released it yet but merged it into a master
You can use master branch for now 
We will update you once we release it

**Comment by crissCM** [comment]
I tried it on the main and even on Afroz-Shaikh:fix-243-interactivity-problem branch, but it doesn't work.

**Comment by hasnentai** [comment]
Can you try 'flutter clean' and 'flutter pub get' once ?

**Comment by hasnentai** [comment]
Also it would be great if you can post the pubspec.ymal here 
Let's see if you are targeting correct deps

**Comment by crissCM** [comment]
Am I doing something wrong?

**Comment by hasnentai** [comment]
hi @crissCM 

Here is the example  https://github.com/GeekyAnts/GaugesFlutter/issues/243#issuecomment-1680223772

make sure you drag your pointer from the center of the needle . Drag from the edge is not working

**Comment by crissCM** [comment]
@Afroz-Shaikh In your video example the ShapePointer interactivity works flawlessly within a ListView. That's exactly what I need right now. How did you make it work like that?

**Comment by hasnentai** [comment]
Hi @Afroz-Shaikh Please post the example here 
@crissCM Please take a look at showcase app of Radial Gauge 

https://gauges-showcase.vercel.app/radial

Check the Air purifier Example.

**Comment by Afroz-Shaikh** [comment]
Is There any specific Widget you are using that's causing it not to work on your end ? @crissCM

**Comment by crissCM** [comment]
I can't make it work. Are you on Flutter 3 as well? Did you try it on Android?
I created a new project, added the main branch as dependency, pasted your code and the ShapePointer is not interactable.
I attached the project zip.
[testy.zip](https://github.com/GeekyAnts/GaugesFlutter/files/12361418/testy.zip)


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3324], locale hu-HU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by crissCM** [comment]
Same simulator that you used:
https://github.com/GeekyAnts/GaugesFlutter/assets/78145538/db5147ad-3335-4ddd-bdf8-d3e31507c2e9

**Comment by crissCM** [comment]
Same simulator that you used:

https://github.com/GeekyAnts/GaugesFlutter/assets/78145538/c94ecc48-4a8f-4d13-85d1-47b9054d8fde

**Comment by crissCM** [comment]
I had a DropDown library widget in a Column before the Gauge stuff and that caused the problems. Now the ShapePointer works perfectly in a ListView. Thank you for this fantastic library and all your help!

**Comment by crissCM** [comment]
I experience some weird behaviour. Usually It works perfectly for a few tries but then just stops interacting for good.
I attached my sample project. I got rid of every possible widgets that can break things, but this problem keeps happening. And it's really inconsistent for me. Sometimes it works for a few tries, sometimes not even for the first try. If you try to run this project, do you experience the same?

https://github.com/GeekyAnts/GaugesFlutter/assets/78145538/8dce5774-b06f-49b1-b029-d44e26356ed2

[test.zip](https://github.com/GeekyAnts/GaugesFlutter/files/12370260/test.zip)

Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3324], locale hu-HU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by crissCM** [comment]
Do you experience the same behavior?

**Comment by edmgithub** [comment]
I have this problem as well. The ShapePointer interactivity doesn't work properly in a ListView.

**Comment by crissCM** [comment]
@Afroz-Shaikh Can you reproduce this issue?
https://github.com/GeekyAnts/GaugesFlutter/pull/244#issuecomment-1682355932

**Comment by somodikrisztian1** [comment]
Has anyone been able to resolve this issue?

**Pull request merged**
